# Generated by Django 4.2 on 2024-11-14 23:43

import Recette.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le titre ne doit contenir que des lettres, chiffres et espaces.', regex='^[a-zA-Z0-9 ]+$')])),
                ('description', models.TextField()),
                ('inventory', models.TextField(help_text="Liste d'ingrédients")),
                ('instructions', models.TextField()),
                ('cook_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Le temps de cuisson doit être au moins 1 minute.')])),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Le nombre de portions doit être au moins 1.'), django.core.validators.MaxValueValidator(20, 'Le nombre de portions doit être au maximum 20.')])),
                ('cuisine', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Facile', 'Facile'), ('Moyen', 'Moyen'), ('Difficile', 'Difficile')], help_text='Niveau de difficulté: Facile, Moyen, Difficile', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', validators=[Recette.models.validate_image_file])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='User.client')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-created_at'],
            },
        ),
    ]
