# Generated by Django 5.1.4 on 2024-12-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='favorites',
        ),
    ]
