# Generated by Django 4.2 on 2024-11-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_admin_options_alter_client_options_and_more'),
        ('Recette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='User.client'),
        ),
    ]
