# Generated by Django 5.1.4 on 2024-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0002_remove_recette_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='inventory',
        ),
        migrations.AddField(
            model_name='recette',
            name='inventory_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
