# Generated by Django 4.2 on 2024-11-07 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('piece_jointe', models.FileField(upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'], message='Only PDF and JPG files are allowed')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
