# Generated by Django 4.2 on 2024-11-14 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='piece_jointe',
            field=models.FileField(upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Only PNG and JPG files are allowed')]),
        ),
    ]
