# Generated by Django 4.2 on 2024-11-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_unit_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Grains', 'Grains')], default='Vegetables', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('liters', 'Liters'), ('pieces', 'Pieces'), ('grams', 'Grams'), ('packs', 'Packs')], default='kg', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
