# Generated by Django 4.2 on 2024-11-14 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Le titre doit contenir au moins 5 caractères.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recette.recette')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
