# Generated by Django 4.2 on 2024-11-08 11:04

import Comment.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Publication', '__first__'),
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[Comment.models.validate_title_case])),
                ('contenu', models.CharField(max_length=255, validators=[Comment.models.validate_no_numbers, Comment.models.validate_no_bad_words, django.core.validators.RegexValidator(message='Content can only contain letters and basic punctuation', regex='^[a-zA-Z\\s.,!?-]*$')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.article')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publication.publication')),
            ],
        ),
    ]
